{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.0/klibnanolog-1.2.0.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-wasm-js-1.2.0.klib",
          "url": "klibnanolog-wasm-js-1.2.0.klib",
          "size": 10930,
          "sha512": "2eef0da754ef96e2dd4fdd2e8e2ddf1fac4f57b79bc606ca755b67d8c590c78217969a6f38911739a922da4635ac573a49ec26b6cd79d5a1b21ae75edc9328c2",
          "sha256": "5cb039bb6a01ec9b4b754b3e2309e481d875e97ed7b7a4815ba557fb17451cc9",
          "sha1": "f35867319f5cd09724540d5658f58d186b8f5073",
          "md5": "b1032794742d0531ad4eafc5cb496d3a"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-wasm-js-1.2.0.klib",
          "url": "klibnanolog-wasm-js-1.2.0.klib",
          "size": 10930,
          "sha512": "2eef0da754ef96e2dd4fdd2e8e2ddf1fac4f57b79bc606ca755b67d8c590c78217969a6f38911739a922da4635ac573a49ec26b6cd79d5a1b21ae75edc9328c2",
          "sha256": "5cb039bb6a01ec9b4b754b3e2309e481d875e97ed7b7a4815ba557fb17451cc9",
          "sha1": "f35867319f5cd09724540d5658f58d186b8f5073",
          "md5": "b1032794742d0531ad4eafc5cb496d3a"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "klibnanolog-wasm-js-1.2.0-sources.jar",
          "url": "klibnanolog-wasm-js-1.2.0-sources.jar",
          "size": 4817,
          "sha512": "7cdc1d715a91fe658869cb20aa3e004118bb6697883273ba1daa03268a9087a8dc2e8e9128501b10bd0c249bb29d808632f44e40bab92aa83a183b387535ca6e",
          "sha256": "e150e8b1fcedb072278410dd794bcf1f45804a2e6066b476e01da50cd1093ee6",
          "sha1": "14564321ddea24443dc9c756cfd7f0367ca09221",
          "md5": "729b03d649b2f6ee41659cd1c5c57ebb"
        }
      ]
    }
  ]
}
