{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.2-SNAPSHOT/klibnanolog-1.2.2-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog.aar",
          "url": "klibnanolog-android-1.2.2-SNAPSHOT.aar",
          "size": 5749,
          "sha512": "df8caf5864870bd39ff8ab7dca17c97416008bad9cadd906341a9130779aaacf52b7ae2be1f835d86bd425508f9c247ce6f6e262cf375da97a454d11ef6208c9",
          "sha256": "04a1429281c40914b09be540abd5cfd6c907a3255fed27652ae05ed821b7a7d7",
          "sha1": "2764b915dc03071e98dc8aef18cbe863417a4b4d",
          "md5": "8b85d28198f572f1f2dbcc8a22781463"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog.aar",
          "url": "klibnanolog-android-1.2.2-SNAPSHOT.aar",
          "size": 5749,
          "sha512": "df8caf5864870bd39ff8ab7dca17c97416008bad9cadd906341a9130779aaacf52b7ae2be1f835d86bd425508f9c247ce6f6e262cf375da97a454d11ef6208c9",
          "sha256": "04a1429281c40914b09be540abd5cfd6c907a3255fed27652ae05ed821b7a7d7",
          "sha1": "2764b915dc03071e98dc8aef18cbe863417a4b4d",
          "md5": "8b85d28198f572f1f2dbcc8a22781463"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "klibnanolog-android-1.2.2-SNAPSHOT-sources.jar",
          "url": "klibnanolog-android-1.2.2-SNAPSHOT-sources.jar",
          "size": 3280,
          "sha512": "0fb5c36b91b28e3740cdb0121fa403024fc92a191ca3bd1b3dad809a9e0ec0b62a214f1a862a9a1f4b84f993d2b4a906eb79b43cb11ad44382a604dc3bdcffed",
          "sha256": "4bb3b8c12ca81fc74f9e9b851d45e2145151e304d08eb82d815dbc1d124f5bc0",
          "sha1": "4aa099e6c741d20956f15037934b3fa5e3a0e9c3",
          "md5": "c2458b590260bbee42f845231a6d0fed"
        }
      ]
    }
  ]
}
