{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.1-SNAPSHOT/klibnanolog-1.2.1-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-macosArm64Main-1.2.1-SNAPSHOT.klib",
          "url": "klibnanolog-macosarm64-1.2.1-SNAPSHOT.klib",
          "size": 10644,
          "sha512": "ced5bcdd7107eab805d47e923d998d32f451fd7f7ebd232944072fb9f5d772186a095e7cc64bf0898638441e2cba1fc5e53bf85f8f078a4cf25903d7366b6a66",
          "sha256": "ca0f62ec546424799b911f25036829e0f20a6e40bab8357e4e79d7d438447c3f",
          "sha1": "18ce566db8f9012752aaed7ba0ba2d071975a79c",
          "md5": "321e87843c1c41a2b7ee1a67d90132e5"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-macosarm64-1.2.1-SNAPSHOT-sources.jar",
          "url": "klibnanolog-macosarm64-1.2.1-SNAPSHOT-sources.jar",
          "size": 4874,
          "sha512": "7741e59ed147e69552c290c0cec8f0f265ab3f11f28366a35563607ceeb4cf4f55da543b0497ffb9fabdd70b12160b1e3a355bf912ad5b9b6a8db53e7b9bebc8",
          "sha256": "442cefcc885296008572562b87ee0442793386fbd5d1891286dbfbbcbfba9e12",
          "sha1": "0389ca20f3e8fe835475310968bc94de24a885b6",
          "md5": "210ae50378f0596260a56080bf004292"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-macosarm64-1.2.1-SNAPSHOT-metadata.jar",
          "url": "klibnanolog-macosarm64-1.2.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
