{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-metadata-1.1.1-SNAPSHOT.jar",
          "url": "klibnanolog-1.1.1-SNAPSHOT.jar",
          "size": 5151,
          "sha512": "5e5e51cabab33f11c8a2742b1a00930fd55a0212620361660a3a5c4e0a86868edb60722063a177a110ac03dbd28c5bcdb1cb4652fd171d146ac981715de0c027",
          "sha256": "7c71ffb5f85f7a1b3aa816424d848699f2659cd72d42337e335c29acd3f605f6",
          "sha1": "6943b015bea7dc8e4d9d873a9af5a2c7848f4d09",
          "md5": "e11aceab9ac8f6b59619a977a6b89212"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "klibnanolog-kotlin-1.1.1-SNAPSHOT-sources.jar",
          "url": "klibnanolog-1.1.1-SNAPSHOT-sources.jar",
          "size": 3545,
          "sha512": "069a8becb52ed5acf8a1244eaafc7fdf3db98c7c6c9ece1aa3c34687d40f1fc4fc8c4f0bc32d4a3f2fea05f79864edf369887561ea9234d8fa4dd475a755d251",
          "sha256": "6ec906c3ad4fb5f43afa1901f03ab061862a350acd3ff1e5bd44d379ee69f83e",
          "sha1": "2c75fe64c150372df6d28a6bd100e7fbbcb0671b",
          "md5": "df9c5d948fa708354a2005701d47685e"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../klibnanolog-js/1.1.1-SNAPSHOT/klibnanolog-js-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-js",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../klibnanolog-js/1.1.1-SNAPSHOT/klibnanolog-js-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-js",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../klibnanolog-js/1.1.1-SNAPSHOT/klibnanolog-js-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-js",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibnanolog-jvm/1.1.1-SNAPSHOT/klibnanolog-jvm-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-jvm",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibnanolog-jvm/1.1.1-SNAPSHOT/klibnanolog-jvm-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-jvm",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibnanolog-jvm/1.1.1-SNAPSHOT/klibnanolog-jvm-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-jvm",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibnanolog-linuxarm64/1.1.1-SNAPSHOT/klibnanolog-linuxarm64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-linuxarm64",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibnanolog-linuxarm64/1.1.1-SNAPSHOT/klibnanolog-linuxarm64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-linuxarm64",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibnanolog-linuxx64/1.1.1-SNAPSHOT/klibnanolog-linuxx64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-linuxx64",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibnanolog-linuxx64/1.1.1-SNAPSHOT/klibnanolog-linuxx64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-linuxx64",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibnanolog-macosarm64/1.1.1-SNAPSHOT/klibnanolog-macosarm64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-macosarm64",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibnanolog-macosarm64/1.1.1-SNAPSHOT/klibnanolog-macosarm64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-macosarm64",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibnanolog-macosarm64/1.1.1-SNAPSHOT/klibnanolog-macosarm64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-macosarm64",
        "version": "1.1.1-SNAPSHOT"
      }
    }
  ]
}
