{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-metadata-1.1.1-SNAPSHOT.jar",
          "url": "klibnanolog-1.1.1-SNAPSHOT.jar",
          "size": 8232,
          "sha512": "f869f11213b230ac381da6927273fe9f0534047ac6f531f5bfc73c08beac7e3ffd7e924feaebe33563d924d1bf9dcd459a2cd3cf6a5bfad575eddd431a3d8b8f",
          "sha256": "2fd8aaa90e7d5859c64f1600b21ee5532b1a7b6545e2c36482e1eb1c5ffe229e",
          "sha1": "c4f981075fb7f80542fcdf83f046373eb3b64b57",
          "md5": "c925ec817b3e92304b383a93d11adac3"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "klibnanolog-kotlin-1.1.1-SNAPSHOT-sources.jar",
          "url": "klibnanolog-1.1.1-SNAPSHOT-sources.jar",
          "size": 6093,
          "sha512": "d438c4f32e86420f531a80e5d74955cdf4107409d5ea8a70c1a6b2e77ea875b0c2ec264ec9b4899f3ea7e47e78cc639b633ac78f04684db35c2a0cca20e5c9a1",
          "sha256": "4d169c5ac24a92ee9c597ccef0960e92c2eee697b450aa09d448db86bdc011c6",
          "sha1": "39722b3d1265007026bcac00598bf1d2e78bd231",
          "md5": "2f0bdb6596599e55f36eb3648b1d117a"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../klibnanolog-android/1.1.1-SNAPSHOT/klibnanolog-android-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-android",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../klibnanolog-android/1.1.1-SNAPSHOT/klibnanolog-android-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-android",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../klibnanolog-android/1.1.1-SNAPSHOT/klibnanolog-android-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-android",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../klibnanolog-js/1.1.1-SNAPSHOT/klibnanolog-js-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-js",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../klibnanolog-js/1.1.1-SNAPSHOT/klibnanolog-js-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-js",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../klibnanolog-js/1.1.1-SNAPSHOT/klibnanolog-js-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-js",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibnanolog-jvm/1.1.1-SNAPSHOT/klibnanolog-jvm-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-jvm",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibnanolog-jvm/1.1.1-SNAPSHOT/klibnanolog-jvm-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-jvm",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibnanolog-jvm/1.1.1-SNAPSHOT/klibnanolog-jvm-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-jvm",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibnanolog-linuxarm64/1.1.1-SNAPSHOT/klibnanolog-linuxarm64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-linuxarm64",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibnanolog-linuxarm64/1.1.1-SNAPSHOT/klibnanolog-linuxarm64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-linuxarm64",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibnanolog-linuxx64/1.1.1-SNAPSHOT/klibnanolog-linuxx64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-linuxx64",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibnanolog-linuxx64/1.1.1-SNAPSHOT/klibnanolog-linuxx64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-linuxx64",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibnanolog-macosarm64/1.1.1-SNAPSHOT/klibnanolog-macosarm64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-macosarm64",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibnanolog-macosarm64/1.1.1-SNAPSHOT/klibnanolog-macosarm64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-macosarm64",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibnanolog-macosarm64/1.1.1-SNAPSHOT/klibnanolog-macosarm64-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-macosarm64",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../klibnanolog-wasm-js/1.1.1-SNAPSHOT/klibnanolog-wasm-js-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-wasm-js",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../klibnanolog-wasm-js/1.1.1-SNAPSHOT/klibnanolog-wasm-js-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-wasm-js",
        "version": "1.1.1-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../klibnanolog-wasm-js/1.1.1-SNAPSHOT/klibnanolog-wasm-js-1.1.1-SNAPSHOT.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-wasm-js",
        "version": "1.1.1-SNAPSHOT"
      }
    }
  ]
}
