{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.0/klibnanolog-1.2.0.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-linuxArm64Main-1.2.0.klib",
          "url": "klibnanolog-linuxarm64-1.2.0.klib",
          "size": 11307,
          "sha512": "d9c6a83e4628a8ab2834a1ac8bc59ee919406a684a02f0086df1415a27eb62aeba6f3c5083d022bd1dcee1390b7925c2656bac88fb61a91e2dc5ec0ab9970cfd",
          "sha256": "43cd2236c611a46bfc2270bb4e39eabc0e5f140932e45f0425505c8a24c9ca83",
          "sha1": "7346fa146d67bdfbd6038c9179f52377db8a7511",
          "md5": "3af3ff8277311364388cfa9b240fa878"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-linuxarm64-1.2.0-sources.jar",
          "url": "klibnanolog-linuxarm64-1.2.0-sources.jar",
          "size": 4866,
          "sha512": "952ecbb549c9acf1c8706e6be64262a76409a683ff2ed0661b4462e01a2170b35ff41fddc7f6ea11c85e512668f3c5d2fb2aef97c5d98f4a3e6ea0fc3a9960f4",
          "sha256": "6e8e9ac9393d18de5e85d39eee9526c5ed6a49944cbe55497d40056cf6f09f3a",
          "sha1": "32bcaae7d7409daf705c7084a2c392f8233f5e10",
          "md5": "473ea2f96df74204e015f19191b00ca0"
        }
      ]
    }
  ]
}
