{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.1/klibnanolog-1.2.1.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-macosArm64Main-1.2.1.klib",
          "url": "klibnanolog-macosarm64-1.2.1.klib",
          "size": 10638,
          "sha512": "2574d89c67848abe2338338e0d869271a85750edd381584de5bb38bb97888a82f0e5f41c1d26ac560f179167cd625beb341ff1cff160fd68b5b5948d5a92b849",
          "sha256": "6e056309294bfa41b71768becea9c2d946986c298a99fd141175692efa873b44",
          "sha1": "fe931b9af99557c567890bf560648c85b79d343a",
          "md5": "20e769f5ff4becdd056b3f5456cb4f92"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-macosarm64-1.2.1-sources.jar",
          "url": "klibnanolog-macosarm64-1.2.1-sources.jar",
          "size": 4866,
          "sha512": "9dd41e1aeca7edf263482c52b0f07e35e7f0740946127bff8c0c41a490b7b52b8a1374fbe45739a42e4a75b9b5f4b15a2ba13117a2b2d396ad39cd14751a3cda",
          "sha256": "8ffadbb3c167d2a77f3d8eb0a49d28279d5c42991f24dba8535172480b85b8fa",
          "sha1": "838a82fe23d6e20573e406609ea24d342dc5041c",
          "md5": "6f1e195b07dda6b04da17b777dff2654"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-macosarm64-1.2.1-metadata.jar",
          "url": "klibnanolog-macosarm64-1.2.1-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
