{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.1.1-SNAPSHOT/klibnanolog-1.1.1-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-js-1.1.1-SNAPSHOT.klib",
          "url": "klibnanolog-js-1.1.1-SNAPSHOT.klib",
          "size": 10928,
          "sha512": "5594244bde112ebfb93910d666262adb4e447624d25c86ba71ff50c674fc4a6a971538740404ffc5753a87167c354bbc27843f0db4fdbd9304e83c241fb3d4a2",
          "sha256": "c5035265fc559ad91bf4ea55130a04344d9fe36481f73681be4c54bde5106f70",
          "sha1": "ba15f91cf0277a4a538ee5ab8a66748ccd5b9234",
          "md5": "645831b3be418cbfe8043041f2e78494"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-js-1.1.1-SNAPSHOT.klib",
          "url": "klibnanolog-js-1.1.1-SNAPSHOT.klib",
          "size": 10928,
          "sha512": "5594244bde112ebfb93910d666262adb4e447624d25c86ba71ff50c674fc4a6a971538740404ffc5753a87167c354bbc27843f0db4fdbd9304e83c241fb3d4a2",
          "sha256": "c5035265fc559ad91bf4ea55130a04344d9fe36481f73681be4c54bde5106f70",
          "sha1": "ba15f91cf0277a4a538ee5ab8a66748ccd5b9234",
          "md5": "645831b3be418cbfe8043041f2e78494"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "klibnanolog-js-1.1.1-SNAPSHOT-sources.jar",
          "url": "klibnanolog-js-1.1.1-SNAPSHOT-sources.jar",
          "size": 4824,
          "sha512": "f7a69ca95c010dc1d5ce9087381d0ab0da0473c74933e84484ea07f1f05fc51b458ba16842eabf6a812b63355898f90c7b84d30e347d82395294526b1aef74ab",
          "sha256": "3664dd55484a45297607d29861d37ab2f501d2f5b002b49dc82481483dccd477",
          "sha1": "d56de67127ceefc4f5e907b2850627193b9aa2ee",
          "md5": "d0e40c61d7c4a33f32443b15fa755d2f"
        }
      ]
    }
  ]
}
