{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.1.1-SNAPSHOT/klibnanolog-1.1.1-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-js-1.1.1-SNAPSHOT.klib",
          "url": "klibnanolog-js-1.1.1-SNAPSHOT.klib",
          "size": 10174,
          "sha512": "9bad0efea40d1e9c7902ad6c8b19f5f0664a6feb40ffe37ad52e682417c1bcf16a75c1512e9614ab9d744670b627e4b5edc65074adfa31bacc988e6a8ec17607",
          "sha256": "8d1909ec54766945580ee2ab3448d1646ccec58d21a87a48f2cd7d48352ff145",
          "sha1": "7a9cdfd802918eec730e21ea0ea63b9a190b1235",
          "md5": "39c13f520ba4ee7d0f70ef305d620c83"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-js-1.1.1-SNAPSHOT.klib",
          "url": "klibnanolog-js-1.1.1-SNAPSHOT.klib",
          "size": 10174,
          "sha512": "9bad0efea40d1e9c7902ad6c8b19f5f0664a6feb40ffe37ad52e682417c1bcf16a75c1512e9614ab9d744670b627e4b5edc65074adfa31bacc988e6a8ec17607",
          "sha256": "8d1909ec54766945580ee2ab3448d1646ccec58d21a87a48f2cd7d48352ff145",
          "sha1": "7a9cdfd802918eec730e21ea0ea63b9a190b1235",
          "md5": "39c13f520ba4ee7d0f70ef305d620c83"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "klibnanolog-js-1.1.1-SNAPSHOT-sources.jar",
          "url": "klibnanolog-js-1.1.1-SNAPSHOT-sources.jar",
          "size": 3427,
          "sha512": "0c4d8eeb4f0c55319e2b2793592b67033deb1d0650c461ee69e3781618138ebb4ae0752c9591d4b2d3f717e45248b5f3d85788c6b42e0f0ea340e5cc17750dd6",
          "sha256": "40f2ddddaee88135632ffd6ac088921c77698ad330b6600dfb73da92a115a8ad",
          "sha1": "377be3d28f8e9bdf4a2506eab2ecb0e7edc76c91",
          "md5": "93453839990b566d1af82457d47309a5"
        }
      ]
    }
  ]
}
