{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.1-SNAPSHOT/klibnanolog-1.2.1-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog.aar",
          "url": "klibnanolog-android-1.2.1-SNAPSHOT.aar",
          "size": 5747,
          "sha512": "9d7543fde7beb8f47cdb99a1ce96f0875dc7eb0fb98ca4640a19140f618eb07bdf0ef7bc8550a296f5e9feeda6a43a54eaf26d88133fc381864e84bfc5574855",
          "sha256": "1cbda3d9fe39e373db185fefd226716123a46d97a4b1756b3500aea33582376c",
          "sha1": "61f429203969e95f4b131fed4f628403f058bad6",
          "md5": "05a7e0a6c58a4dd73a7527393edf317d"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog.aar",
          "url": "klibnanolog-android-1.2.1-SNAPSHOT.aar",
          "size": 5747,
          "sha512": "9d7543fde7beb8f47cdb99a1ce96f0875dc7eb0fb98ca4640a19140f618eb07bdf0ef7bc8550a296f5e9feeda6a43a54eaf26d88133fc381864e84bfc5574855",
          "sha256": "1cbda3d9fe39e373db185fefd226716123a46d97a4b1756b3500aea33582376c",
          "sha1": "61f429203969e95f4b131fed4f628403f058bad6",
          "md5": "05a7e0a6c58a4dd73a7527393edf317d"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "klibnanolog-android-1.2.1-SNAPSHOT-sources.jar",
          "url": "klibnanolog-android-1.2.1-SNAPSHOT-sources.jar",
          "size": 3280,
          "sha512": "1b62108f28eb547701e9e7c914a5b9c888f764d2a10c1297263c2cd8dae3241db6700358febe330d81ac3eaea585cad35ff02a488ee1c09948f086a71b5fd956",
          "sha256": "e30261df6d1a39d7593aa57787c071b33701ab446cc1f193ef99b4a70b98cab3",
          "sha1": "a74c3d47d7416ed2a95e9d0f6e000b093380c66a",
          "md5": "b0574e15936f44eca2d7d9d86dc92551"
        }
      ]
    }
  ]
}
