{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.1-SNAPSHOT/klibnanolog-1.2.1-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-wasm-js-1.2.1-SNAPSHOT.klib",
          "url": "klibnanolog-wasm-js-1.2.1-SNAPSHOT.klib",
          "size": 10268,
          "sha512": "26c2198335bc0242df2415ad57b69f992ff6606de1bff6f9512557693a1625ff00a43a33b7928c6769217b7648db802c559d0dec4d24ab4efd5c7d7b3ba2da0c",
          "sha256": "55c4e58b6371681d38d4f6ae750f0803d6e694aa89a36d2299393590dd16878c",
          "sha1": "c5567daae123e8f8a82eaf15900a23f4fdecdc79",
          "md5": "bd2b32ab05e7436a7fe092a5a3e90648"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-wasm-js-1.2.1-SNAPSHOT.klib",
          "url": "klibnanolog-wasm-js-1.2.1-SNAPSHOT.klib",
          "size": 10268,
          "sha512": "26c2198335bc0242df2415ad57b69f992ff6606de1bff6f9512557693a1625ff00a43a33b7928c6769217b7648db802c559d0dec4d24ab4efd5c7d7b3ba2da0c",
          "sha256": "55c4e58b6371681d38d4f6ae750f0803d6e694aa89a36d2299393590dd16878c",
          "sha1": "c5567daae123e8f8a82eaf15900a23f4fdecdc79",
          "md5": "bd2b32ab05e7436a7fe092a5a3e90648"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "klibnanolog-wasm-js-1.2.1-SNAPSHOT-sources.jar",
          "url": "klibnanolog-wasm-js-1.2.1-SNAPSHOT-sources.jar",
          "size": 4825,
          "sha512": "95b0ff31547bc87753cb3acfdaaf54ff42ff7146620148deccf0963228fd5dc68aac4cc8d2ddaafd1a98fade95cbe4d8e91dbba94f25fb7aebfdf30e7514584e",
          "sha256": "3538355b88dde2f12282a8c3f3ca7401137592e01b64017ade65d309c21816fa",
          "sha1": "f11fe1536bebc8c1975667bd16608cb66bcf1b8f",
          "md5": "dd902148e0b9059adab9bb2728087787"
        }
      ]
    }
  ]
}
