{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.0/klibnanolog-1.2.0.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-js-1.2.0.klib",
          "url": "klibnanolog-js-1.2.0.klib",
          "size": 10924,
          "sha512": "16ba4ea9b23414fabb4ca7b672572b6d0ae6f9dff577025e05de186b9659fd8b3eb465916d99871d4a91a34fdb738129eaf76aa0bd760e12dfe04a3ae9e1c4ce",
          "sha256": "c1ceb74524de417f3475a4423859964dc3f1e9ca4b3fa1bc5ccc5a52c3a37b4b",
          "sha1": "bed48d21ab417faaeb8aa22d42f932e4b6ad56f5",
          "md5": "19a6887b980628c33dd1033ced16f574"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-js-1.2.0.klib",
          "url": "klibnanolog-js-1.2.0.klib",
          "size": 10924,
          "sha512": "16ba4ea9b23414fabb4ca7b672572b6d0ae6f9dff577025e05de186b9659fd8b3eb465916d99871d4a91a34fdb738129eaf76aa0bd760e12dfe04a3ae9e1c4ce",
          "sha256": "c1ceb74524de417f3475a4423859964dc3f1e9ca4b3fa1bc5ccc5a52c3a37b4b",
          "sha1": "bed48d21ab417faaeb8aa22d42f932e4b6ad56f5",
          "md5": "19a6887b980628c33dd1033ced16f574"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "klibnanolog-js-1.2.0-sources.jar",
          "url": "klibnanolog-js-1.2.0-sources.jar",
          "size": 4817,
          "sha512": "7cdc1d715a91fe658869cb20aa3e004118bb6697883273ba1daa03268a9087a8dc2e8e9128501b10bd0c249bb29d808632f44e40bab92aa83a183b387535ca6e",
          "sha256": "e150e8b1fcedb072278410dd794bcf1f45804a2e6066b476e01da50cd1093ee6",
          "sha1": "14564321ddea24443dc9c756cfd7f0367ca09221",
          "md5": "729b03d649b2f6ee41659cd1c5c57ebb"
        }
      ]
    }
  ]
}
