{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.1/klibnanolog-1.2.1.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-js-1.2.1.klib",
          "url": "klibnanolog-js-1.2.1.klib",
          "size": 10226,
          "sha512": "6bdbef8db5d492b89bd30f7b32ccd5a692215af2ad5966ea8d94058c8854c09679719c2e4187511c02e1981a46e81048a56cd8faa2ffd15b64c8662830d2cba2",
          "sha256": "b5f7cd69366c57972c2f25d0ed6b5e46e0d9ace6b82dac02218b1f7a58a2cb2b",
          "sha1": "ed1d42d80cd262ad850719d47650d3ff0951ff16",
          "md5": "4b3e5f97ed5613f03ca1f411e28f9eca"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-js-1.2.1.klib",
          "url": "klibnanolog-js-1.2.1.klib",
          "size": 10226,
          "sha512": "6bdbef8db5d492b89bd30f7b32ccd5a692215af2ad5966ea8d94058c8854c09679719c2e4187511c02e1981a46e81048a56cd8faa2ffd15b64c8662830d2cba2",
          "sha256": "b5f7cd69366c57972c2f25d0ed6b5e46e0d9ace6b82dac02218b1f7a58a2cb2b",
          "sha1": "ed1d42d80cd262ad850719d47650d3ff0951ff16",
          "md5": "4b3e5f97ed5613f03ca1f411e28f9eca"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "klibnanolog-js-1.2.1-sources.jar",
          "url": "klibnanolog-js-1.2.1-sources.jar",
          "size": 4817,
          "sha512": "ee7ce5d8973903eadadccabbd26040ec5de8a71f63e59e3457062deb7d2ba9f9ea3f22134cabb45c7ac8181113434fcbdaa7841a2e98ee6fe8eb6986e48693f1",
          "sha256": "aa99b2ac95ffcb99e48ebedb67048d058b2c3f685bd1f33db5d60fb0d8fb524e",
          "sha1": "68c4248a80cc17c23951ab1f904107a46c42a66a",
          "md5": "d417c3c6e13e8de1cbd0c2ffc77706ac"
        }
      ]
    }
  ]
}
