{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.0/klibnanolog-1.2.0.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-macosArm64Main-1.2.0.klib",
          "url": "klibnanolog-macosarm64-1.2.0.klib",
          "size": 11301,
          "sha512": "f6af4c37e39acbb31e505ddd36251946c3c4c43e7f266ec5e5b95057ff71fc45803d5f4017ddec85f8a7d5b28aca25fcfd0787a670026bbdbc0fb4ac0859df6d",
          "sha256": "736f9efe09e5cb5e889e3345362c0ea541672fda842f06785739446bf881e462",
          "sha1": "43635cda5145b1e576013716aa954d61ca144441",
          "md5": "a5f00584395cf1fefdd0b1950aec643c"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-macosarm64-1.2.0-sources.jar",
          "url": "klibnanolog-macosarm64-1.2.0-sources.jar",
          "size": 4866,
          "sha512": "952ecbb549c9acf1c8706e6be64262a76409a683ff2ed0661b4462e01a2170b35ff41fddc7f6ea11c85e512668f3c5d2fb2aef97c5d98f4a3e6ea0fc3a9960f4",
          "sha256": "6e8e9ac9393d18de5e85d39eee9526c5ed6a49944cbe55497d40056cf6f09f3a",
          "sha1": "32bcaae7d7409daf705c7084a2c392f8233f5e10",
          "md5": "473ea2f96df74204e015f19191b00ca0"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-macosarm64-1.2.0-metadata.jar",
          "url": "klibnanolog-macosarm64-1.2.0-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
