{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.0.1/klibnanolog-1.0.1.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-linuxX64Main-1.0.1.klib",
          "url": "klibnanolog-linuxx64-1.0.1.klib",
          "size": 10587,
          "sha512": "ee9256ebd94380e7bc03aaf0effb4c16a547a58a83a56458b5f36ff5ad03ebeb80fd41e57034c823c2594d3f97b843c884c8cb296bb5cce5e294431497dba310",
          "sha256": "d3fb27df93451b4698f9ea47bd8b92a117cd55b0b78afb1c1a803b1f88c796e9",
          "sha1": "cf1f3ef8e6252efa2af35f1b32435206cbf0931a",
          "md5": "6269fb34ae4890b04ea0c56739455765"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-linuxx64-1.0.1-sources.jar",
          "url": "klibnanolog-linuxx64-1.0.1-sources.jar",
          "size": 3538,
          "sha512": "f46d944c69f684b7a1807dcea6fe9e61610abb2723b5982bc767705bddd30d65c3f3de44cccc83e51cb5ca100d0c37e0653b2381f85d9225e303a9880b3e49c0",
          "sha256": "6b6295330f9836810a646f30035bc0fc5cb2acdd305a424846e34d888b1a7c29",
          "sha1": "5593809f3e63b9d99a0c73b5ec93f682bc0767d3",
          "md5": "5386c243463b29ee6feb95b733303113"
        }
      ]
    }
  ]
}
