{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.1/klibnanolog-1.2.1.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-jvm-1.2.1.jar",
          "url": "klibnanolog-jvm-1.2.1.jar",
          "size": 13435,
          "sha512": "d4f672e85b14e7a0912369df2b11f89a0a805e7b1d5779fa81ec62d8ae48afffa7dd81c76b8164cf8dfdae14d961f7c968096dc126ee263da419a84282c45112",
          "sha256": "ce76d9fbb8611f292fe3265a0c614395760f61ddf22f3cd0a810696669e29fd7",
          "sha1": "d5d420398daeb5d324355a42d0f96776bb4c8e43",
          "md5": "c2901e6f6c566619d36ae4f42531f06d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.18"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-jvm-1.2.1.jar",
          "url": "klibnanolog-jvm-1.2.1.jar",
          "size": 13435,
          "sha512": "d4f672e85b14e7a0912369df2b11f89a0a805e7b1d5779fa81ec62d8ae48afffa7dd81c76b8164cf8dfdae14d961f7c968096dc126ee263da419a84282c45112",
          "sha256": "ce76d9fbb8611f292fe3265a0c614395760f61ddf22f3cd0a810696669e29fd7",
          "sha1": "d5d420398daeb5d324355a42d0f96776bb4c8e43",
          "md5": "c2901e6f6c566619d36ae4f42531f06d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibnanolog-jvm-1.2.1-sources.jar",
          "url": "klibnanolog-jvm-1.2.1-sources.jar",
          "size": 7892,
          "sha512": "2473f924fb3fb4b9c1231f791574884ec9f115f29ae454b61e7b7115de14dff30877a5139fc904c40df9aaa5a8a121e85032333b208bfd61b731f74c80bd482a",
          "sha256": "513e84d42633ee07dcc3f4c04d43a47468e84326ea7b863079104f352f71e8b8",
          "sha1": "b70d18bb6e39b61a882b53da29b90f5ad85890bc",
          "md5": "a86649634544e3041b2417261279315a"
        }
      ]
    }
  ]
}
