{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.2-SNAPSHOT/klibnanolog-1.2.2-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-js-1.2.2-SNAPSHOT.klib",
          "url": "klibnanolog-js-1.2.2-SNAPSHOT.klib",
          "size": 10236,
          "sha512": "4c86811328f59293dc76c04008e42980848c00164ca47bd832acf35f7dd3f7c455e079c68f4e9fcfd58170a71bc635f98cd9c888ef3f242390da50ac55dad07a",
          "sha256": "161b8c95cfb54dd867332eda541ff2d622011a04edd4f8f38877edfcd3159968",
          "sha1": "f928e0684779fd31db2252389238548d7c01131a",
          "md5": "c004e6806b8d81b3721c819ad9874e0a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-js-1.2.2-SNAPSHOT.klib",
          "url": "klibnanolog-js-1.2.2-SNAPSHOT.klib",
          "size": 10236,
          "sha512": "4c86811328f59293dc76c04008e42980848c00164ca47bd832acf35f7dd3f7c455e079c68f4e9fcfd58170a71bc635f98cd9c888ef3f242390da50ac55dad07a",
          "sha256": "161b8c95cfb54dd867332eda541ff2d622011a04edd4f8f38877edfcd3159968",
          "sha1": "f928e0684779fd31db2252389238548d7c01131a",
          "md5": "c004e6806b8d81b3721c819ad9874e0a"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "klibnanolog-js-1.2.2-SNAPSHOT-sources.jar",
          "url": "klibnanolog-js-1.2.2-SNAPSHOT-sources.jar",
          "size": 4825,
          "sha512": "55dfc142596404813a67f68e93ee1da02f35c7d5ac176d877d153cc30188d4c01b390a75fd9fdb904909aeedb9bb94bd337e1bfff047793d71ef8a59d47560a5",
          "sha256": "2598a288291a10023211338bdb55a1af258704d939acf98d797448d0e8e804a4",
          "sha1": "c8e919d66a58caaca6c39a960cc72955d3a09b85",
          "md5": "81da54b2f00cbe5e18025fb1ad912776"
        }
      ]
    }
  ]
}
