{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.0.2-SNAPSHOT/klibnanolog-1.0.2-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-jvm-1.0.2-SNAPSHOT.jar",
          "url": "klibnanolog-jvm-1.0.2-SNAPSHOT.jar",
          "size": 7133,
          "sha512": "c60e675743efdf9a6b420539f9fc54d5d6bf704495238c7ea6e388e9df1ac7afc3768e2a6a1a6a786e114796bb247da92c50ce60e736caef47fd494536ffb6c8",
          "sha256": "f7d314d3106bde7982a90a38e5a660205e595bd318dfd0c140ef0e0513fd0f9e",
          "sha1": "204e09737d91583bf7954b163b9a5487af1b0ef6",
          "md5": "5b4af8556f3b405e67e44f34db7eab95"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-jvm-1.0.2-SNAPSHOT.jar",
          "url": "klibnanolog-jvm-1.0.2-SNAPSHOT.jar",
          "size": 7133,
          "sha512": "c60e675743efdf9a6b420539f9fc54d5d6bf704495238c7ea6e388e9df1ac7afc3768e2a6a1a6a786e114796bb247da92c50ce60e736caef47fd494536ffb6c8",
          "sha256": "f7d314d3106bde7982a90a38e5a660205e595bd318dfd0c140ef0e0513fd0f9e",
          "sha1": "204e09737d91583bf7954b163b9a5487af1b0ef6",
          "md5": "5b4af8556f3b405e67e44f34db7eab95"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibnanolog-jvm-1.0.2-SNAPSHOT-sources.jar",
          "url": "klibnanolog-jvm-1.0.2-SNAPSHOT-sources.jar",
          "size": 3442,
          "sha512": "f10d02a505713f05a07892ab5d03d265a0a1feae2fc7d9a6fb0c19814ea8fee7ae4d79466616bd424301664b702137661c442ad5307b94898fd9dccf44d4f5b5",
          "sha256": "927689948d3f70aeb16dc932698bdc414c5c0feaeb2b6355b9bea14aafb9ad17",
          "sha1": "b4eed11e5059a63b6d607161da9e03a57a51281e",
          "md5": "818d360325d24f6e16db1d2526dc40cb"
        }
      ]
    }
  ]
}
