{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.2-SNAPSHOT/klibnanolog-1.2.2-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-iosSimulatorArm64Main-1.2.2-SNAPSHOT.klib",
          "url": "klibnanolog-iossimulatorarm64-1.2.2-SNAPSHOT.klib",
          "size": 10694,
          "sha512": "28b028f2bb08245357aa58206f6d36367167cf5fd4c7cf72f637b5caee1ac09e2c913090162fc754c449185ad0fc32cd9cbf59294dc5b083cc7b45f08d72d2e5",
          "sha256": "e093829b8504bb027d2679264907bdeed5826cb3ca2ae710f0ee0e9c9b5d1802",
          "sha1": "cb9a1d5c0f7c6406ac982796c92bf108ace469d2",
          "md5": "8b531989af2d1b1af825e271d0489fa4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-iossimulatorarm64-1.2.2-SNAPSHOT-sources.jar",
          "url": "klibnanolog-iossimulatorarm64-1.2.2-SNAPSHOT-sources.jar",
          "size": 4874,
          "sha512": "85c1f54686c83658823794a9e79397754e3d0c635b7cac8940e975af92ab5c8b7a0811fca10b51a02256801d5dd21ab24c1c89b2eb0fe5d4610c0f2f5f0c2562",
          "sha256": "248bed6fa1e44dbe9eb662551211406baf8d4c4e2a5bf8c177c7bb165a82e411",
          "sha1": "b4afc7f49158b2f9ae3a0846d9b5c25930082316",
          "md5": "dfce91cdf4c19c9ff1f2691bb1010a46"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-iossimulatorarm64-1.2.2-SNAPSHOT-metadata.jar",
          "url": "klibnanolog-iossimulatorarm64-1.2.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
