{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.1.0/klibnanolog-1.1.0.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-linuxArm64Main-1.1.0.klib",
          "url": "klibnanolog-linuxarm64-1.1.0.klib",
          "size": 10602,
          "sha512": "b49f9c29e5a297b91fb49108a03de35081d7cd1a73014a2739a09c62c585eed6bffc9e2aa0493ba716712719c98f0b5134e62037043fe801ef2c0a2a9f28e153",
          "sha256": "1fad55b41d3d580a4bcdb664759e0ccb399c60b0ab37880a65aa06303f6603ad",
          "sha1": "d81a76dc40216c907d9b2f96c92b6529820d5a86",
          "md5": "33705bad209d2036240f16f5864e2c07"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-linuxarm64-1.1.0-sources.jar",
          "url": "klibnanolog-linuxarm64-1.1.0-sources.jar",
          "size": 3538,
          "sha512": "3855a07eb389a2b77b9a22c2bad53d04f02ff3d8ec9ec5aafc7918fc676c886a2c5bd0d01646ca2379ba0e5ab111fe0421c85e3b8667ad6477990ea8e9edb743",
          "sha256": "7ed9cb7ad403b2c23457e78a1051d5c6a46a6b4d705bb53bb22f0582bacf3aa6",
          "sha1": "0ad712f82d04927b5a8dd2e4905b4ff3c281531f",
          "md5": "7a9ee04baf0089cc10f631e453637590"
        }
      ]
    }
  ]
}
