{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.1-SNAPSHOT/klibnanolog-1.2.1-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-jvm-1.2.1-SNAPSHOT.jar",
          "url": "klibnanolog-jvm-1.2.1-SNAPSHOT.jar",
          "size": 13445,
          "sha512": "97844a92ea1cba55215a2eee9645502586b59256a77e7a4d3a67dcaae1ee791f20c4a67c5f625cdd78c875225f078667315b44f6b4ce5ff2ef4d47d6231aa0ca",
          "sha256": "0cbfc407e9cf7b65e7040854f4df3c34ecb0a5663263c564d069d61cdfd176b5",
          "sha1": "d274058c7a910458975b12033d410a5648fe9ef6",
          "md5": "0132b0e8ed4512e74129d90606b40bf0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.18"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-jvm-1.2.1-SNAPSHOT.jar",
          "url": "klibnanolog-jvm-1.2.1-SNAPSHOT.jar",
          "size": 13445,
          "sha512": "97844a92ea1cba55215a2eee9645502586b59256a77e7a4d3a67dcaae1ee791f20c4a67c5f625cdd78c875225f078667315b44f6b4ce5ff2ef4d47d6231aa0ca",
          "sha256": "0cbfc407e9cf7b65e7040854f4df3c34ecb0a5663263c564d069d61cdfd176b5",
          "sha1": "d274058c7a910458975b12033d410a5648fe9ef6",
          "md5": "0132b0e8ed4512e74129d90606b40bf0"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibnanolog-jvm-1.2.1-SNAPSHOT-sources.jar",
          "url": "klibnanolog-jvm-1.2.1-SNAPSHOT-sources.jar",
          "size": 7900,
          "sha512": "04cb277cbfb1f6b298b722a39b50081207f600c251f8d66e8951011bf2e223b7f92b0812bdd9045e9216884255c756cba717265cfc3109c040cd287bf42d9063",
          "sha256": "783db7daa5bf3ed11f0299d188f42095983a58ba925f3458ebdf668dc2b15481",
          "sha1": "039d9d1c53bf7cc1006672d7895a78256cf38674",
          "md5": "26f883c89862c47c6957a9f38150b7b7"
        }
      ]
    }
  ]
}
