{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.1.1-SNAPSHOT/klibnanolog-1.1.1-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-linuxX64Main-1.1.1-SNAPSHOT.klib",
          "url": "klibnanolog-linuxx64-1.1.1-SNAPSHOT.klib",
          "size": 11299,
          "sha512": "8e3919e04b72d73970a6604c8854260d148592edf1293774304725b3800bd44e5ebf2f902dc9337b30196f8f1d5a2c0be7a8a677d0b4c3e77511941092fec1e4",
          "sha256": "5e2d94b0d4df8646e86aa40d347313822e59f10b9cdde6acf7221245bad59f60",
          "sha1": "af84812678cf556698d29daf6c19fd211c689c8b",
          "md5": "1daeff030916b62902be026e15f7a615"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-linuxx64-1.1.1-SNAPSHOT-sources.jar",
          "url": "klibnanolog-linuxx64-1.1.1-SNAPSHOT-sources.jar",
          "size": 4873,
          "sha512": "4c7335ae39c5a1ac53cc1129c10937bcd6c315382dc20e923447250e6a387e1d19a69be6e954b7a68d2215843c9e79a17bc2b999eeb60e3854b09636c2db9a72",
          "sha256": "13c094aecc650c35f5d7c18e0e77d4e950a47aed1be0a6859d03e7985c9b6fdd",
          "sha1": "f8ca3d65cb9685a996af42858a65bca2e7b5dd2b",
          "md5": "4d37ced118032028f28a138647f844b4"
        }
      ]
    }
  ]
}
