{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.1/klibnanolog-1.2.1.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-iosArm64Main-1.2.1.klib",
          "url": "klibnanolog-iosarm64-1.2.1.klib",
          "size": 10624,
          "sha512": "2dd62373060704e852f211bd079da7a7e26856f9b8cea6f60279c039d0409e1434907db0813dba15f74155e002ebecc870add90106f01d58ba637f40ce91588a",
          "sha256": "fd873b4841a285be683703e95785923345e95d6a3d89fd676afe1c42f8d361b0",
          "sha1": "10187a236a2f24ec0a5856323df6b4c6670ecd28",
          "md5": "75211050476bf9b907b6f289a95959d9"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-iosarm64-1.2.1-sources.jar",
          "url": "klibnanolog-iosarm64-1.2.1-sources.jar",
          "size": 4866,
          "sha512": "9dd41e1aeca7edf263482c52b0f07e35e7f0740946127bff8c0c41a490b7b52b8a1374fbe45739a42e4a75b9b5f4b15a2ba13117a2b2d396ad39cd14751a3cda",
          "sha256": "8ffadbb3c167d2a77f3d8eb0a49d28279d5c42991f24dba8535172480b85b8fa",
          "sha1": "838a82fe23d6e20573e406609ea24d342dc5041c",
          "md5": "6f1e195b07dda6b04da17b777dff2654"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-iosarm64-1.2.1-metadata.jar",
          "url": "klibnanolog-iosarm64-1.2.1-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
