{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.2-SNAPSHOT/klibnanolog-1.2.2-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-linuxX64Main-1.2.2-SNAPSHOT.klib",
          "url": "klibnanolog-linuxx64-1.2.2-SNAPSHOT.klib",
          "size": 10630,
          "sha512": "c8abec12bf4cb63187ebe3baeaccdd68c1394ea655f5fb3696fdb63e071cc1c2d91e52c2574026b65c553f1f8d1ead52a723bea924ecc0c34003e9bdf18b240a",
          "sha256": "4c00baa7dfd967481d6e469081abcaf4ba975a63736cfd4799f73314de2d9107",
          "sha1": "ae73641eee0e45b26632cca9f44a9f291a1f3429",
          "md5": "5dca24cecb060a9778fea41dbce875e3"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-linuxx64-1.2.2-SNAPSHOT-sources.jar",
          "url": "klibnanolog-linuxx64-1.2.2-SNAPSHOT-sources.jar",
          "size": 4874,
          "sha512": "306508c6bb9e218eb2913dc86ff4777ff913ea2149a1de82e50163f986a8c870612cb05cc0a44e2339933082305ed34ee84e7cc2a1cf9c084594ffe776770bbc",
          "sha256": "f3b8839274504161f597f1f7ca8c5251660da48b18706259dc89be5d69a65f17",
          "sha1": "36c532039a4ca55077a9c5d7f4de6a244d150d56",
          "md5": "21e768830d557c21d722c21889183ee1"
        }
      ]
    }
  ]
}
