{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.0/klibnanolog-1.2.0.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-linuxX64Main-1.2.0.klib",
          "url": "klibnanolog-linuxx64-1.2.0.klib",
          "size": 11294,
          "sha512": "b585ab54c1a3e6818d2058e9d5d73488c8622047fbb8e8cc5bd038ca06f5bdd7149b1363e68b826c7b5306444bfaeeb44f4f31d4a616542f961dd7b6aa284a97",
          "sha256": "7a2f2c24d56d9023cf9da91b8d2ea315753965729e052c1d7c53fca4bcbe2500",
          "sha1": "043fcfa0f108b51b0bf82e230610dc778aa373b3",
          "md5": "36ec03ef0e88f2b35b41bd844397a904"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-linuxx64-1.2.0-sources.jar",
          "url": "klibnanolog-linuxx64-1.2.0-sources.jar",
          "size": 4866,
          "sha512": "952ecbb549c9acf1c8706e6be64262a76409a683ff2ed0661b4462e01a2170b35ff41fddc7f6ea11c85e512668f3c5d2fb2aef97c5d98f4a3e6ea0fc3a9960f4",
          "sha256": "6e8e9ac9393d18de5e85d39eee9526c5ed6a49944cbe55497d40056cf6f09f3a",
          "sha1": "32bcaae7d7409daf705c7084a2c392f8233f5e10",
          "md5": "473ea2f96df74204e015f19191b00ca0"
        }
      ]
    }
  ]
}
