{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.0.1-SNAPSHOT/klibnanolog-1.0.1-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-jvm-1.0.1-SNAPSHOT.jar",
          "url": "klibnanolog-jvm-1.0.1-SNAPSHOT.jar",
          "size": 7131,
          "sha512": "4d2fdba571ffe10c567e2dc46d1b2c7c5e0ed94bbb14f0ba04baf8699742855912e3f4282d49bfffe46006a6652d6a1b668671ee946037ee0db479e7a33d1f95",
          "sha256": "5811aff4118c653aef7a259621af2947d04205ab59e165f2d20ddb98f424832e",
          "sha1": "dbf647bf0c05659e2f68384c0ee2451db42bfdee",
          "md5": "124a793711067e937a2c9db71a8967cd"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-jvm-1.0.1-SNAPSHOT.jar",
          "url": "klibnanolog-jvm-1.0.1-SNAPSHOT.jar",
          "size": 7131,
          "sha512": "4d2fdba571ffe10c567e2dc46d1b2c7c5e0ed94bbb14f0ba04baf8699742855912e3f4282d49bfffe46006a6652d6a1b668671ee946037ee0db479e7a33d1f95",
          "sha256": "5811aff4118c653aef7a259621af2947d04205ab59e165f2d20ddb98f424832e",
          "sha1": "dbf647bf0c05659e2f68384c0ee2451db42bfdee",
          "md5": "124a793711067e937a2c9db71a8967cd"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibnanolog-jvm-1.0.1-SNAPSHOT-sources.jar",
          "url": "klibnanolog-jvm-1.0.1-SNAPSHOT-sources.jar",
          "size": 3442,
          "sha512": "816db884a7defb63ccd7885aa4c03685598da6342acc3caa0a4e1d0be8d3297f531a163d043b2d6c8922580524c83d4713ec9a09c89f942774c72fe0d9f92c2a",
          "sha256": "5b25de579eb2e710514471ae9673f65bc72f83e8095a50abc8b575b61b4f8ec0",
          "sha1": "efa6139ac02fab0d9c760c89f2b4f303baec4ddf",
          "md5": "2ca357a690ca4c2edb20397db3525065"
        }
      ]
    }
  ]
}
