{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.0.1/klibnanolog-1.0.1.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-js-1.0.1.klib",
          "url": "klibnanolog-js-1.0.1.klib",
          "size": 10224,
          "sha512": "c5ab6c37f1393299c58760e25bdd6bdec34d23c37a60796e8a5ca2498c8aeac0365432efb046db65645c91e159ca4a69a85d5cacbedddde85a2060675c5d5c2d",
          "sha256": "fc444276569a1f0a230609f43cafa03b2133de59299940a6105a98696ec47ee3",
          "sha1": "0df3504c391ed4965bd57e494d59bb12113f58af",
          "md5": "b258ab98d06cdfadf79010dcb0b6b26e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-js-1.0.1.klib",
          "url": "klibnanolog-js-1.0.1.klib",
          "size": 10224,
          "sha512": "c5ab6c37f1393299c58760e25bdd6bdec34d23c37a60796e8a5ca2498c8aeac0365432efb046db65645c91e159ca4a69a85d5cacbedddde85a2060675c5d5c2d",
          "sha256": "fc444276569a1f0a230609f43cafa03b2133de59299940a6105a98696ec47ee3",
          "sha1": "0df3504c391ed4965bd57e494d59bb12113f58af",
          "md5": "b258ab98d06cdfadf79010dcb0b6b26e"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "klibnanolog-js-1.0.1-sources.jar",
          "url": "klibnanolog-js-1.0.1-sources.jar",
          "size": 3420,
          "sha512": "8a8e2049c0192bfccc8cfa7ccfe5d9b5805f7bdf8e176a18371c18837a8faf3ae3b342714af3554428bbdd966cf5377d8e78587678fa878c3ac37a915d749a18",
          "sha256": "f0910bbdfcf992da40c1ac50a1d560b7b5f3296cc6c62fa577f153991b7186ac",
          "sha1": "82a1e5cfcb9aa7e4de1da33da4413dd2a6513b06",
          "md5": "2d47d1924b165b30dd754d4d281dfd31"
        }
      ]
    }
  ]
}
