{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.0.1-SNAPSHOT/klibnanolog-1.0.1-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-macosArm64Main-1.0.1-SNAPSHOT.klib",
          "url": "klibnanolog-macosarm64-1.0.1-SNAPSHOT.klib",
          "size": 10599,
          "sha512": "c8f88c86d4e7b07d99995eab1d80f9e96ac467b63ec3532365c567b2c0a6346aef813c1ecced580808d719f9eff4c5bd6d240b1207ae4226020843dfe148c8a2",
          "sha256": "f30a27f6ce32db12d0b9e2e018517088c5d72b42f2737ff1ed2bc36ace9fc4af",
          "sha1": "c7d0071b659d3536a3c73d891a6e7091acdc0d42",
          "md5": "ac0a74f72a967f36d3d621035e39077c"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-macosarm64-1.0.1-SNAPSHOT-sources.jar",
          "url": "klibnanolog-macosarm64-1.0.1-SNAPSHOT-sources.jar",
          "size": 3546,
          "sha512": "8c31fad2ea8cc4d78d096f68fe5b28bfedfc4a48cd479231f58f34ac3805b1e01fdecc0d322ab99830b4d957fb126e11d50fd89fe0533697183294d235db3118",
          "sha256": "fe18e0f5c5bd61893ec2ef2c631588a5f90c69d31a4d06c4ad5a653c69978ce4",
          "sha1": "7b155ef98dda1e1b081526a640663d2cdde722ca",
          "md5": "35c18544f57b14b3ae58b31d6f16e94a"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-macosarm64-1.0.1-SNAPSHOT-metadata.jar",
          "url": "klibnanolog-macosarm64-1.0.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
