{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.2-SNAPSHOT/klibnanolog-1.2.2-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-macosArm64Main-1.2.2-SNAPSHOT.klib",
          "url": "klibnanolog-macosarm64-1.2.2-SNAPSHOT.klib",
          "size": 10644,
          "sha512": "8adaee10b97b0878b385c2db5ab40245414434b2f9ad31d5d5cc88c16386f335f2bc383fe1c26a10e9a2c5f3dd36743342391f6f51cd538cfd3a2834877bd1a2",
          "sha256": "18410c721ecde777c9b3c28334cc42006a76d03938e26c5f04138a4a6016f249",
          "sha1": "e05be891f17dd1187d3b780ccd106824d1126e46",
          "md5": "529fd5d2885e94c38ef3176afcd5db11"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-macosarm64-1.2.2-SNAPSHOT-sources.jar",
          "url": "klibnanolog-macosarm64-1.2.2-SNAPSHOT-sources.jar",
          "size": 4874,
          "sha512": "85c1f54686c83658823794a9e79397754e3d0c635b7cac8940e975af92ab5c8b7a0811fca10b51a02256801d5dd21ab24c1c89b2eb0fe5d4610c0f2f5f0c2562",
          "sha256": "248bed6fa1e44dbe9eb662551211406baf8d4c4e2a5bf8c177c7bb165a82e411",
          "sha1": "b4afc7f49158b2f9ae3a0846d9b5c25930082316",
          "md5": "dfce91cdf4c19c9ff1f2691bb1010a46"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-macosarm64-1.2.2-SNAPSHOT-metadata.jar",
          "url": "klibnanolog-macosarm64-1.2.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
