{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.0.1-SNAPSHOT/klibnanolog-1.0.1-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-js-1.0.1-SNAPSHOT.klib",
          "url": "klibnanolog-js-1.0.1-SNAPSHOT.klib",
          "size": 10232,
          "sha512": "ecfa7a5a9149218b2b227f723d12d497de3a8a181586cbb1076c560d93b178f922a238339e4def92122342d31225e5751e72dd6bb98307abd0ef0b1449825082",
          "sha256": "391be9060f8bcc5f0fda6aa37af5d219e654199ce1bccc1704498b0ceb30237e",
          "sha1": "13a6f7739f229776226fa123d99ae716a05cda10",
          "md5": "d0c69aefd19d5a8b141784729cb1e2f8"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-js-1.0.1-SNAPSHOT.klib",
          "url": "klibnanolog-js-1.0.1-SNAPSHOT.klib",
          "size": 10232,
          "sha512": "ecfa7a5a9149218b2b227f723d12d497de3a8a181586cbb1076c560d93b178f922a238339e4def92122342d31225e5751e72dd6bb98307abd0ef0b1449825082",
          "sha256": "391be9060f8bcc5f0fda6aa37af5d219e654199ce1bccc1704498b0ceb30237e",
          "sha1": "13a6f7739f229776226fa123d99ae716a05cda10",
          "md5": "d0c69aefd19d5a8b141784729cb1e2f8"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "klibnanolog-js-1.0.1-SNAPSHOT-sources.jar",
          "url": "klibnanolog-js-1.0.1-SNAPSHOT-sources.jar",
          "size": 3428,
          "sha512": "9e88a81c1d935bb534960d30ec49d68620760765dbcb6e47c4268f1041d22273f7bdeb6a766f60561f2a63373d2c42a897df81d0b91c49d9565d81f5f64b0929",
          "sha256": "ca0813ed28149e2673a1838406a2495f5f8ae526dc0bdd47b0eb6494e61346b1",
          "sha1": "3ad2f9748712134e0257c46a15b31063fecc9576",
          "md5": "cf1c0de3fd8b7f5bbeec0083195d9f7f"
        }
      ]
    }
  ]
}
