{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.1/klibnanolog-1.2.1.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-wasm-js-1.2.1.klib",
          "url": "klibnanolog-wasm-js-1.2.1.klib",
          "size": 10262,
          "sha512": "4c352338482d7e0f6544cb1c001b3138e8452bed2ef5538c025519878f102d25b24378d5045fabcd5535610b068a97d940a886915a89c1b078de0a40cc8630ca",
          "sha256": "ffd8f8ea56cc8075193a414ea05f5271dba393e73e8453fec593dfede7d15840",
          "sha1": "b23d27e0ffcc1cf775ed846fd871093cd8788f0f",
          "md5": "75d97ef025671d267b2e8666aa52d33d"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-wasm-js-1.2.1.klib",
          "url": "klibnanolog-wasm-js-1.2.1.klib",
          "size": 10262,
          "sha512": "4c352338482d7e0f6544cb1c001b3138e8452bed2ef5538c025519878f102d25b24378d5045fabcd5535610b068a97d940a886915a89c1b078de0a40cc8630ca",
          "sha256": "ffd8f8ea56cc8075193a414ea05f5271dba393e73e8453fec593dfede7d15840",
          "sha1": "b23d27e0ffcc1cf775ed846fd871093cd8788f0f",
          "md5": "75d97ef025671d267b2e8666aa52d33d"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "klibnanolog-wasm-js-1.2.1-sources.jar",
          "url": "klibnanolog-wasm-js-1.2.1-sources.jar",
          "size": 4817,
          "sha512": "ee7ce5d8973903eadadccabbd26040ec5de8a71f63e59e3457062deb7d2ba9f9ea3f22134cabb45c7ac8181113434fcbdaa7841a2e98ee6fe8eb6986e48693f1",
          "sha256": "aa99b2ac95ffcb99e48ebedb67048d058b2c3f685bd1f33db5d60fb0d8fb524e",
          "sha1": "68c4248a80cc17c23951ab1f904107a46c42a66a",
          "md5": "d417c3c6e13e8de1cbd0c2ffc77706ac"
        }
      ]
    }
  ]
}
