{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.1/klibnanolog-1.2.1.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-linuxX64Main-1.2.1.klib",
          "url": "klibnanolog-linuxx64-1.2.1.klib",
          "size": 10623,
          "sha512": "fcd779d6a40d0e5d1cd86bca29e9d44b7136df6e861c51ffc55cb0748c31d5ec37771e93e6faf7871b507f0e3867a730595867c7a01aa3030bd70cfb8ea1ed72",
          "sha256": "eaf5f6e7cfaddc45c356df8d5eb5928245cd744b73fd14248dc0e6702d50999f",
          "sha1": "749ba2838e1300bc6ad2a4c80a8518a27378e127",
          "md5": "61cff310e0e4bf88a772fe21a6cadbe2"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-linuxx64-1.2.1-sources.jar",
          "url": "klibnanolog-linuxx64-1.2.1-sources.jar",
          "size": 4866,
          "sha512": "9dd41e1aeca7edf263482c52b0f07e35e7f0740946127bff8c0c41a490b7b52b8a1374fbe45739a42e4a75b9b5f4b15a2ba13117a2b2d396ad39cd14751a3cda",
          "sha256": "8ffadbb3c167d2a77f3d8eb0a49d28279d5c42991f24dba8535172480b85b8fa",
          "sha1": "838a82fe23d6e20573e406609ea24d342dc5041c",
          "md5": "6f1e195b07dda6b04da17b777dff2654"
        }
      ]
    }
  ]
}
