{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.1.0/klibnanolog-1.1.0.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-macosArm64Main-1.1.0.klib",
          "url": "klibnanolog-macosarm64-1.1.0.klib",
          "size": 10594,
          "sha512": "a4193d3b1f77a4500e7abd7b399e9880981bd47c7a58a7fdf8341b2872464f71765dcb45184735ae0abe66a9588f4863a3450b7922740ddc90b2b777a2f347d8",
          "sha256": "c97e3d909bae4d749fc8d9de91c6e12608b5fd2a052bdf927389e2efd1df7c26",
          "sha1": "3787858ebd9b1ca3401bd0ddffcda1562de3f4ce",
          "md5": "3ac8633105976e4c9946d63281e4356d"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-macosarm64-1.1.0-sources.jar",
          "url": "klibnanolog-macosarm64-1.1.0-sources.jar",
          "size": 3538,
          "sha512": "3855a07eb389a2b77b9a22c2bad53d04f02ff3d8ec9ec5aafc7918fc676c886a2c5bd0d01646ca2379ba0e5ab111fe0421c85e3b8667ad6477990ea8e9edb743",
          "sha256": "7ed9cb7ad403b2c23457e78a1051d5c6a46a6b4d705bb53bb22f0582bacf3aa6",
          "sha1": "0ad712f82d04927b5a8dd2e4905b4ff3c281531f",
          "md5": "7a9ee04baf0089cc10f631e453637590"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-macosarm64-1.1.0-metadata.jar",
          "url": "klibnanolog-macosarm64-1.1.0-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
