{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.1.1-SNAPSHOT/klibnanolog-1.1.1-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-jvm-1.1.1-SNAPSHOT.jar",
          "url": "klibnanolog-jvm-1.1.1-SNAPSHOT.jar",
          "size": 13334,
          "sha512": "ea3f78fbff576570251a54a1127fb72e4545ae52ec8228720393d1baea8f5c7a1c4d7cf76ae85f16896c29d316a70d9c1b4823e2256e560e507d213e4f70385a",
          "sha256": "85d331e69592318fa1d369e9b176708e41958edf0975f9b8590f7ea96a69a3dd",
          "sha1": "ac73bb4bf4e7cd6aa5cde440095a71368049fa07",
          "md5": "848ee7e0b14b5c4e8edf2f857047115a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-jvm-1.1.1-SNAPSHOT.jar",
          "url": "klibnanolog-jvm-1.1.1-SNAPSHOT.jar",
          "size": 13334,
          "sha512": "ea3f78fbff576570251a54a1127fb72e4545ae52ec8228720393d1baea8f5c7a1c4d7cf76ae85f16896c29d316a70d9c1b4823e2256e560e507d213e4f70385a",
          "sha256": "85d331e69592318fa1d369e9b176708e41958edf0975f9b8590f7ea96a69a3dd",
          "sha1": "ac73bb4bf4e7cd6aa5cde440095a71368049fa07",
          "md5": "848ee7e0b14b5c4e8edf2f857047115a"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibnanolog-jvm-1.1.1-SNAPSHOT-sources.jar",
          "url": "klibnanolog-jvm-1.1.1-SNAPSHOT-sources.jar",
          "size": 7899,
          "sha512": "91b3efdbae114e0375e495be3fe963ecc3d874c742784acbea6790d73e35487b4323e2968be709b592d14131ae57ff44f6731a66a0239f2c19a96db164633047",
          "sha256": "acad9e1b8737e69a64ad139b83eedafe939f051d7cf5603272ac7fdf279a5703",
          "sha1": "a877131abe495aa3ea1d4641c2f066f2a944e982",
          "md5": "ee2d2af33ff2a9d3a90c4b91b5a11a08"
        }
      ]
    }
  ]
}
