{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.0.2-SNAPSHOT/klibnanolog-1.0.2-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-linuxX64Main-1.0.2-SNAPSHOT.klib",
          "url": "klibnanolog-linuxx64-1.0.2-SNAPSHOT.klib",
          "size": 10594,
          "sha512": "8589c8a4ab4c2bdc8e0c60d105c4d76beb9da858891cf16b785e8b2f2ef45d8029d258fa7cbcb59e39bbca595fbd40119490f9ef3f04d3dddc7dbb718e9cfe0e",
          "sha256": "02b72664fdde91c3633661283e5e94caf4638d0f5caf14db4835a9c7e322b799",
          "sha1": "7fac0e5e9d4909a2876efcd65d7fce2bdaff00aa",
          "md5": "0950cfb8603fa20b12e7ae042186d3ee"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-linuxx64-1.0.2-SNAPSHOT-sources.jar",
          "url": "klibnanolog-linuxx64-1.0.2-SNAPSHOT-sources.jar",
          "size": 3546,
          "sha512": "a8bdd0d2aede317743591b62fbfdea43f2bb49af343a58063c9f5b2c6f2abb35e0fbeb5c0685a5fbb250eaeb9058f3d6b62a0ce1c86e507825d15f7fc284336e",
          "sha256": "1013a351e44d744952fed0ffaf5b04e1ba95bfdb263c88d9d24e2d5b22d71d01",
          "sha1": "39b3d4c8f57d2ff4a594301cbf39a261e3cd2d78",
          "md5": "06d31652c0d6bcfc3a6d883452be1b92"
        }
      ]
    }
  ]
}
