{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-metadata-1.0.1.jar",
          "url": "klibnanolog-1.0.1.jar",
          "size": 5147,
          "sha512": "6494fffe3b169f70b8e7ba171aa650588fc172ac1201cd5348f76b12e9ff50a885eb74d715bcde43b75eb23dbdc81f5a1a04721d07a7bb6bb2e82d35021fbf3b",
          "sha256": "ce68d205aa93d8e3f11d585e541fa33fe5b682a0ff68fbca5407ddaf32da6355",
          "sha1": "ea39041277baf82db420c91b4af26427c58c6ec7",
          "md5": "5c8a978fca2e2ffeb5e5cfaa7971e1ad"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "klibnanolog-kotlin-1.0.1-sources.jar",
          "url": "klibnanolog-1.0.1-sources.jar",
          "size": 3538,
          "sha512": "40375c42d6f6c42efd36bdc97c53df65f056e1ae656682710396b0a29d6245fd43515ff58e5d4dc27bc2927529b9a88538d2a857ec6abaaedaf258a769526484",
          "sha256": "fa7252a25309434ccb7e075048843955174aa3d7d5d1d8c7352f84a1e26d9762",
          "sha1": "1a5e06a1641aba8429a523a99c65c0ba028126a6",
          "md5": "e332bffcf969478c560e27a4764b33df"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../klibnanolog-js/1.0.1/klibnanolog-js-1.0.1.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-js",
        "version": "1.0.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../klibnanolog-js/1.0.1/klibnanolog-js-1.0.1.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-js",
        "version": "1.0.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../klibnanolog-js/1.0.1/klibnanolog-js-1.0.1.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-js",
        "version": "1.0.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibnanolog-jvm/1.0.1/klibnanolog-jvm-1.0.1.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-jvm",
        "version": "1.0.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibnanolog-jvm/1.0.1/klibnanolog-jvm-1.0.1.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-jvm",
        "version": "1.0.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibnanolog-jvm/1.0.1/klibnanolog-jvm-1.0.1.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-jvm",
        "version": "1.0.1"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibnanolog-linuxarm64/1.0.1/klibnanolog-linuxarm64-1.0.1.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-linuxarm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibnanolog-linuxarm64/1.0.1/klibnanolog-linuxarm64-1.0.1.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-linuxarm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibnanolog-linuxx64/1.0.1/klibnanolog-linuxx64-1.0.1.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-linuxx64",
        "version": "1.0.1"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibnanolog-linuxx64/1.0.1/klibnanolog-linuxx64-1.0.1.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-linuxx64",
        "version": "1.0.1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibnanolog-macosarm64/1.0.1/klibnanolog-macosarm64-1.0.1.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-macosarm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibnanolog-macosarm64/1.0.1/klibnanolog-macosarm64-1.0.1.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-macosarm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibnanolog-macosarm64/1.0.1/klibnanolog-macosarm64-1.0.1.module",
        "group": "org.jraf.klibnanolog",
        "module": "klibnanolog-macosarm64",
        "version": "1.0.1"
      }
    }
  ]
}
