{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.0.2-SNAPSHOT/klibnanolog-1.0.2-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-js-1.0.2-SNAPSHOT.klib",
          "url": "klibnanolog-js-1.0.2-SNAPSHOT.klib",
          "size": 10233,
          "sha512": "d39f50e4be07b291ed3f745e696f6b3b6e9172dc4f6f8be76bafec9c553af48ede296ba3a1d6926e72eaf2120da0cf3ba5abb1688022d2b6da69a6ed9ff027ee",
          "sha256": "edf12e39f910d9b9680701e79e367e2ebd70fcfe38ace82d365bc22087774b69",
          "sha1": "0112e857f1d8d49662f59ee24851305be4b7ded7",
          "md5": "14aa2cbd531985f1a781b7868e815d17"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-js-1.0.2-SNAPSHOT.klib",
          "url": "klibnanolog-js-1.0.2-SNAPSHOT.klib",
          "size": 10233,
          "sha512": "d39f50e4be07b291ed3f745e696f6b3b6e9172dc4f6f8be76bafec9c553af48ede296ba3a1d6926e72eaf2120da0cf3ba5abb1688022d2b6da69a6ed9ff027ee",
          "sha256": "edf12e39f910d9b9680701e79e367e2ebd70fcfe38ace82d365bc22087774b69",
          "sha1": "0112e857f1d8d49662f59ee24851305be4b7ded7",
          "md5": "14aa2cbd531985f1a781b7868e815d17"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "klibnanolog-js-1.0.2-SNAPSHOT-sources.jar",
          "url": "klibnanolog-js-1.0.2-SNAPSHOT-sources.jar",
          "size": 3428,
          "sha512": "0acacb03c329ffd9b23de5e11409cd04bda2218928b3794245bd2511170f6ad370829f4e7ef664d96960a5d6b7f26a385d2f299b20d92b49066e445d100b730f",
          "sha256": "b0880e75b6793678507754ffb3aee908eb61a714dcfa0486b73532567480d11d",
          "sha1": "d9ef56b4f755ac0b62eb0048486414e563ed58b6",
          "md5": "d6f8cfe6d742a6306bed5a0e5416ebeb"
        }
      ]
    }
  ]
}
