{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.1.0/klibnanolog-1.1.0.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-js-1.1.0.klib",
          "url": "klibnanolog-js-1.1.0.klib",
          "size": 10167,
          "sha512": "d3e566beb01ff07efa0eacdaa01d630d5af403ddbc1d999ddd98ade5b01dfe8b308030b298fece2db3adfa7efd7c233de1c72dc2053999f4e24a1fd0cbbd7168",
          "sha256": "c6c7ce0ace79dc8ff32776081fa1d474b7d7e9518962d426b04b1024392b9f93",
          "sha1": "fa5be60790fe3dfcc342a6a19e349a4402c99d46",
          "md5": "21daa824a5385314b170a3f3f25065b6"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-js-1.1.0.klib",
          "url": "klibnanolog-js-1.1.0.klib",
          "size": 10167,
          "sha512": "d3e566beb01ff07efa0eacdaa01d630d5af403ddbc1d999ddd98ade5b01dfe8b308030b298fece2db3adfa7efd7c233de1c72dc2053999f4e24a1fd0cbbd7168",
          "sha256": "c6c7ce0ace79dc8ff32776081fa1d474b7d7e9518962d426b04b1024392b9f93",
          "sha1": "fa5be60790fe3dfcc342a6a19e349a4402c99d46",
          "md5": "21daa824a5385314b170a3f3f25065b6"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "klibnanolog-js-1.1.0-sources.jar",
          "url": "klibnanolog-js-1.1.0-sources.jar",
          "size": 3420,
          "sha512": "35e01948376e0a4cd93b57b8b665ea822b1f8bfce0d32b1476cda5e0b20f820d6e2a08c33a61c5d545c053db1ac354755c90c7b7b4316054a9b2725adc18c39f",
          "sha256": "a6f010eb89528169f14eec8f8a17fbc0ca6f4d01cc8add11d1208d2de88771de",
          "sha1": "c6a4088d2406429421123643959ece549b53ae2b",
          "md5": "c084b855b1939b06ce7035bec32e9b0f"
        }
      ]
    }
  ]
}
