{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.1/klibnanolog-1.2.1.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-linuxArm64Main-1.2.1.klib",
          "url": "klibnanolog-linuxarm64-1.2.1.klib",
          "size": 10636,
          "sha512": "e667c71434f3b1e90a25a795edd6e8d035d13120e5b3d9cf72dda2f4e1b8a446450e6a23a33e5d57e4039daa9d240c2d776341cd423facada78eb204549c6588",
          "sha256": "6493303968dd1dac84e017b1bb221ef8e19b65c2392f0151f6d3567407d4fc50",
          "sha1": "da021af7967e261ed2a979510db8881f1e23eae2",
          "md5": "8b8f0a9bc2f27cf127c58e9da366ce73"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-linuxarm64-1.2.1-sources.jar",
          "url": "klibnanolog-linuxarm64-1.2.1-sources.jar",
          "size": 4866,
          "sha512": "9dd41e1aeca7edf263482c52b0f07e35e7f0740946127bff8c0c41a490b7b52b8a1374fbe45739a42e4a75b9b5f4b15a2ba13117a2b2d396ad39cd14751a3cda",
          "sha256": "8ffadbb3c167d2a77f3d8eb0a49d28279d5c42991f24dba8535172480b85b8fa",
          "sha1": "838a82fe23d6e20573e406609ea24d342dc5041c",
          "md5": "6f1e195b07dda6b04da17b777dff2654"
        }
      ]
    }
  ]
}
