{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.1.0/klibnanolog-1.1.0.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-linuxX64Main-1.1.0.klib",
          "url": "klibnanolog-linuxx64-1.1.0.klib",
          "size": 10589,
          "sha512": "503a2b82e8ca7389850686b1ba97864213cc4796fe4663bcfd1cc94ffe367f41878d5f648e0a0329ae67ac9813186f10cd2b48110c70515774c085f6cc24461f",
          "sha256": "74c225c101fa9a453190f45875e4b623f4cdfd95c9c4668b0824db5883b90ec9",
          "sha1": "250acfaa4e4c70194aa6ad4c3ad8cf2c21c84168",
          "md5": "6fa1736811d0fc751b70819ac866e079"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-linuxx64-1.1.0-sources.jar",
          "url": "klibnanolog-linuxx64-1.1.0-sources.jar",
          "size": 3538,
          "sha512": "3855a07eb389a2b77b9a22c2bad53d04f02ff3d8ec9ec5aafc7918fc676c886a2c5bd0d01646ca2379ba0e5ab111fe0421c85e3b8667ad6477990ea8e9edb743",
          "sha256": "7ed9cb7ad403b2c23457e78a1051d5c6a46a6b4d705bb53bb22f0582bacf3aa6",
          "sha1": "0ad712f82d04927b5a8dd2e4905b4ff3c281531f",
          "md5": "7a9ee04baf0089cc10f631e453637590"
        }
      ]
    }
  ]
}
