{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.1.1-SNAPSHOT/klibnanolog-1.1.1-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-linuxArm64Main-1.1.1-SNAPSHOT.klib",
          "url": "klibnanolog-linuxarm64-1.1.1-SNAPSHOT.klib",
          "size": 11312,
          "sha512": "d6a5e1df052974c75529876dff442f8ce78a1fc9cef600644605c3faef246afef028bfd7d48cb6c5435261709faf7e298804677c9eb68248c7ddba1acbfef6ae",
          "sha256": "f62dea5519ce96ffd354ff738d16daa3453eb3b7588d208eb936daff39df5713",
          "sha1": "d365b87cadbb55baa88223e60947be211b78cb58",
          "md5": "fd2519801bae883b377bb6d4cbdb6c26"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-linuxarm64-1.1.1-SNAPSHOT-sources.jar",
          "url": "klibnanolog-linuxarm64-1.1.1-SNAPSHOT-sources.jar",
          "size": 4873,
          "sha512": "4c7335ae39c5a1ac53cc1129c10937bcd6c315382dc20e923447250e6a387e1d19a69be6e954b7a68d2215843c9e79a17bc2b999eeb60e3854b09636c2db9a72",
          "sha256": "13c094aecc650c35f5d7c18e0e77d4e950a47aed1be0a6859d03e7985c9b6fdd",
          "sha1": "f8ca3d65cb9685a996af42858a65bca2e7b5dd2b",
          "md5": "4d37ced118032028f28a138647f844b4"
        }
      ]
    }
  ]
}
