{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.1.1-SNAPSHOT/klibnanolog-1.1.1-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-linuxArm64Main-1.1.1-SNAPSHOT.klib",
          "url": "klibnanolog-linuxarm64-1.1.1-SNAPSHOT.klib",
          "size": 10607,
          "sha512": "3f5b3ebb134ba133a2f077475fe2873af0b5c4871223553e72864a5017263887b5b546bc7fbda8f93c4b5e9fbf5667072a61cef01df5d4a85a6b0329cf129117",
          "sha256": "9bf6fb0810e9e473c24408899b574a2ed57f7effbc11392f3275fc59c43cb472",
          "sha1": "29d0d6e81968c7246f8799f83de08411507474f8",
          "md5": "3973029073f47890a80520e0ab4f94e9"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-linuxarm64-1.1.1-SNAPSHOT-sources.jar",
          "url": "klibnanolog-linuxarm64-1.1.1-SNAPSHOT-sources.jar",
          "size": 3545,
          "sha512": "76e13a0ca8841226dc2a5850817e53491a2ce7874abbd85db554f7ac88c34fdb083ff966346c52d9e08ca006f20b201b964d9bbd936587cece8a0878379d5b6f",
          "sha256": "a86adb8f376a7644131153d84102fb09d96ea1aa72e85dd5dbcecb116fb0ccbd",
          "sha1": "e8765b710a6172bb348ac056eeb1baa47687ce9d",
          "md5": "5c9fb4e472483241f38ffec7b5e2bd4f"
        }
      ]
    }
  ]
}
