{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.0.2-SNAPSHOT/klibnanolog-1.0.2-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-macosArm64Main-1.0.2-SNAPSHOT.klib",
          "url": "klibnanolog-macosarm64-1.0.2-SNAPSHOT.klib",
          "size": 10600,
          "sha512": "2d4c4a981b286bbb27589b177b6da2f87bc0db5fb33418a4f50d9df7f736ed51dbaf1c66dfa006c90ec569f8d0e401dab13d91dd5f050fb06351612dfeb1f910",
          "sha256": "42ec9e33107af08d02fc2dae7b018a79d25e81dde5bc4b7900fd381fdb94d558",
          "sha1": "4678b4891252a5c5331764d1140268e6cf9db31a",
          "md5": "ed82bdf1d38c194305bc755b48d204e2"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-macosarm64-1.0.2-SNAPSHOT-sources.jar",
          "url": "klibnanolog-macosarm64-1.0.2-SNAPSHOT-sources.jar",
          "size": 3546,
          "sha512": "a8bdd0d2aede317743591b62fbfdea43f2bb49af343a58063c9f5b2c6f2abb35e0fbeb5c0685a5fbb250eaeb9058f3d6b62a0ce1c86e507825d15f7fc284336e",
          "sha256": "1013a351e44d744952fed0ffaf5b04e1ba95bfdb263c88d9d24e2d5b22d71d01",
          "sha1": "39b3d4c8f57d2ff4a594301cbf39a261e3cd2d78",
          "md5": "06d31652c0d6bcfc3a6d883452be1b92"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-macosarm64-1.0.2-SNAPSHOT-metadata.jar",
          "url": "klibnanolog-macosarm64-1.0.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
