{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.0/klibnanolog-1.2.0.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog.aar",
          "url": "klibnanolog-android-1.2.0.aar",
          "size": 5689,
          "sha512": "0ebdd2745a1adab14a4d7fd467984622309a4327eef09a9481c06825ab4d0b7952140c90c6d99f3d3648714e77fbfc62ddc01081297062d8a8ba2d21d995a6bb",
          "sha256": "d92fc417a56371c75820f30977c75531dea7d69e92b63f0356c3261b97298c79",
          "sha1": "eb880341eef5e802521cf55972ceea2f097001e3",
          "md5": "1eaed3c83a54711b4f66b796e3dc22b1"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog.aar",
          "url": "klibnanolog-android-1.2.0.aar",
          "size": 5689,
          "sha512": "0ebdd2745a1adab14a4d7fd467984622309a4327eef09a9481c06825ab4d0b7952140c90c6d99f3d3648714e77fbfc62ddc01081297062d8a8ba2d21d995a6bb",
          "sha256": "d92fc417a56371c75820f30977c75531dea7d69e92b63f0356c3261b97298c79",
          "sha1": "eb880341eef5e802521cf55972ceea2f097001e3",
          "md5": "1eaed3c83a54711b4f66b796e3dc22b1"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "klibnanolog-android-1.2.0-sources.jar",
          "url": "klibnanolog-android-1.2.0-sources.jar",
          "size": 3272,
          "sha512": "0c57bb87313154c83b81a6cc4903fd973ef94a1db4c90be59265a3288b7b8876affafccb6b2c07df013d2bcd3554c77a865584dd5b950f9f4f52a0e1dbc14792",
          "sha256": "590686abf5b99518711d9df5b36bfaf97a169a5dabcfb17b412760f4f15a2b70",
          "sha1": "252c61b4213112fb423455ec1bcac7ea865c4621",
          "md5": "f0f474726f675d0411f88345e50952e2"
        }
      ]
    }
  ]
}
