{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.0.1/klibnanolog-1.0.1.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-linuxArm64Main-1.0.1.klib",
          "url": "klibnanolog-linuxarm64-1.0.1.klib",
          "size": 10600,
          "sha512": "dfc8e0bca4acd22768c7b1783ebeb09af8f732348c1ce9fd3f5bffaab7ea3a59db5734b8a7d7b7a1165fb38ec802519c8d421cdd9a25ae8335decedf0b7e640f",
          "sha256": "1ebeb6b641749598775c5bd7c551bed5b7e4072f0f54feffc9da94bff610d476",
          "sha1": "5c96578eadbc682f2e8a803024a251528dd53c9c",
          "md5": "efe63375c1c3840faf5893101f27d978"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-linuxarm64-1.0.1-sources.jar",
          "url": "klibnanolog-linuxarm64-1.0.1-sources.jar",
          "size": 3538,
          "sha512": "f46d944c69f684b7a1807dcea6fe9e61610abb2723b5982bc767705bddd30d65c3f3de44cccc83e51cb5ca100d0c37e0653b2381f85d9225e303a9880b3e49c0",
          "sha256": "6b6295330f9836810a646f30035bc0fc5cb2acdd305a424846e34d888b1a7c29",
          "sha1": "5593809f3e63b9d99a0c73b5ec93f682bc0767d3",
          "md5": "5386c243463b29ee6feb95b733303113"
        }
      ]
    }
  ]
}
