{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.0/klibnanolog-1.2.0.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-jvm-1.2.0.jar",
          "url": "klibnanolog-jvm-1.2.0.jar",
          "size": 13327,
          "sha512": "fe57a354a5ed456ffef5d59d1ae55fc4b8697fcda9ccf1694a73fdad3512a327270e7813b3d98321ef9436b61f9267270700028e2503b5be4e4fbdc86022a5df",
          "sha256": "c144af8aaffabdb631e67868d47f6263e0c3036ef9378af4f4b5430d900b97f2",
          "sha1": "518f31bff57cb621fd0aac6c12fb75360ce55df5",
          "md5": "3dcefacd860de7932eede12187f8801f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-jvm-1.2.0.jar",
          "url": "klibnanolog-jvm-1.2.0.jar",
          "size": 13327,
          "sha512": "fe57a354a5ed456ffef5d59d1ae55fc4b8697fcda9ccf1694a73fdad3512a327270e7813b3d98321ef9436b61f9267270700028e2503b5be4e4fbdc86022a5df",
          "sha256": "c144af8aaffabdb631e67868d47f6263e0c3036ef9378af4f4b5430d900b97f2",
          "sha1": "518f31bff57cb621fd0aac6c12fb75360ce55df5",
          "md5": "3dcefacd860de7932eede12187f8801f"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibnanolog-jvm-1.2.0-sources.jar",
          "url": "klibnanolog-jvm-1.2.0-sources.jar",
          "size": 7892,
          "sha512": "826a580ff70e34099948372563636bf70866b63465fad4406effc45593d3fa8709a663150793006759f1285f577e736f3b8be6fe5bbc03e60887c0c9c31a721f",
          "sha256": "f80d03fe1c14971ebfd6acac086d05904c38923e87c9fca14ae41a5b2c124984",
          "sha1": "81c019ae9e4a5563193ace757493f3481626b32b",
          "md5": "661c5aef8430b5435839408fafa376fa"
        }
      ]
    }
  ]
}
