{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.1-SNAPSHOT/klibnanolog-1.2.1-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-js-1.2.1-SNAPSHOT.klib",
          "url": "klibnanolog-js-1.2.1-SNAPSHOT.klib",
          "size": 10235,
          "sha512": "16e7ac70f74dd7ac7a4af087a4b12e2ab751396d671964c0bb68bcfd44a73a37b4c092522329a676cb0a91d6eb2a71cfbc0cc01d11ae9c0d4a0ded31d5ea3123",
          "sha256": "695200d29f1ea3c24269f0607b2f505b12d310f4a167e4c05b82c4ce8e547dd8",
          "sha1": "2c0707ed1e729ff229642fa4459364419631eb5c",
          "md5": "cc8f8133ea249231b6c259d433b9b2e9"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-js-1.2.1-SNAPSHOT.klib",
          "url": "klibnanolog-js-1.2.1-SNAPSHOT.klib",
          "size": 10235,
          "sha512": "16e7ac70f74dd7ac7a4af087a4b12e2ab751396d671964c0bb68bcfd44a73a37b4c092522329a676cb0a91d6eb2a71cfbc0cc01d11ae9c0d4a0ded31d5ea3123",
          "sha256": "695200d29f1ea3c24269f0607b2f505b12d310f4a167e4c05b82c4ce8e547dd8",
          "sha1": "2c0707ed1e729ff229642fa4459364419631eb5c",
          "md5": "cc8f8133ea249231b6c259d433b9b2e9"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "klibnanolog-js-1.2.1-SNAPSHOT-sources.jar",
          "url": "klibnanolog-js-1.2.1-SNAPSHOT-sources.jar",
          "size": 4825,
          "sha512": "95b0ff31547bc87753cb3acfdaaf54ff42ff7146620148deccf0963228fd5dc68aac4cc8d2ddaafd1a98fade95cbe4d8e91dbba94f25fb7aebfdf30e7514584e",
          "sha256": "3538355b88dde2f12282a8c3f3ca7401137592e01b64017ade65d309c21816fa",
          "sha1": "f11fe1536bebc8c1975667bd16608cb66bcf1b8f",
          "md5": "dd902148e0b9059adab9bb2728087787"
        }
      ]
    }
  ]
}
