{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.0.1/klibnanolog-1.0.1.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-macosArm64Main-1.0.1.klib",
          "url": "klibnanolog-macosarm64-1.0.1.klib",
          "size": 10592,
          "sha512": "560f308328c4a3b2b652a907a2b7ba17fcebe86829daa25017fae31f8f7a91ca9b795cf63522c332e0ad86db3c79c6ffbc82e847037f7d6e98d7bf7b5160a3a9",
          "sha256": "7d7b5676a6df38812bb281469ed958ad27e93aec2ea82a2123dd5492419dd0e3",
          "sha1": "f99687a8c05f55994b41a6fcca1c53550af5ac26",
          "md5": "816687c2d45a5e83b580def171c6a597"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-macosarm64-1.0.1-sources.jar",
          "url": "klibnanolog-macosarm64-1.0.1-sources.jar",
          "size": 3538,
          "sha512": "f46d944c69f684b7a1807dcea6fe9e61610abb2723b5982bc767705bddd30d65c3f3de44cccc83e51cb5ca100d0c37e0653b2381f85d9225e303a9880b3e49c0",
          "sha256": "6b6295330f9836810a646f30035bc0fc5cb2acdd305a424846e34d888b1a7c29",
          "sha1": "5593809f3e63b9d99a0c73b5ec93f682bc0767d3",
          "md5": "5386c243463b29ee6feb95b733303113"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-macosarm64-1.0.1-metadata.jar",
          "url": "klibnanolog-macosarm64-1.0.1-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
