{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.0.1-SNAPSHOT/klibnanolog-1.0.1-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-linuxArm64Main-1.0.1-SNAPSHOT.klib",
          "url": "klibnanolog-linuxarm64-1.0.1-SNAPSHOT.klib",
          "size": 10607,
          "sha512": "eabfe1d8c5a1fc88236f037858939fb98152a00569d0984691892870be25a50dc7cd111b508930cd91052d798c462e5e146bd464e9f19dd291eb667d1d7a281b",
          "sha256": "97040a78fdd6942a1a75984eb6ebe512449439d086517d3315e1d906679aee29",
          "sha1": "b48a5d70481a232e307d4b75b67f5a62ffb6816b",
          "md5": "03ed23ca86902d067497cfe61629f62e"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "klibnanolog-linuxarm64-1.0.1-SNAPSHOT-sources.jar",
          "url": "klibnanolog-linuxarm64-1.0.1-SNAPSHOT-sources.jar",
          "size": 3546,
          "sha512": "8c31fad2ea8cc4d78d096f68fe5b28bfedfc4a48cd479231f58f34ac3805b1e01fdecc0d322ab99830b4d957fb126e11d50fd89fe0533697183294d235db3118",
          "sha256": "fe18e0f5c5bd61893ec2ef2c631588a5f90c69d31a4d06c4ad5a653c69978ce4",
          "sha1": "7b155ef98dda1e1b081526a640663d2cdde722ca",
          "md5": "35c18544f57b14b3ae58b31d6f16e94a"
        }
      ]
    }
  ]
}
