{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnanolog/1.2.2-SNAPSHOT/klibnanolog-1.2.2-SNAPSHOT.module",
    "group": "org.jraf.klibnanolog",
    "module": "klibnanolog",
    "version": "1.2.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-wasm-js-1.2.2-SNAPSHOT.klib",
          "url": "klibnanolog-wasm-js-1.2.2-SNAPSHOT.klib",
          "size": 10268,
          "sha512": "c217de3a4441c926700f6b90a49f642534fb4f9584a14bf12244ac624d1a6252e7935b51cada57e43e4bd51c7000f09fb7a2f09c15072cbf1ac86b916efb29c1",
          "sha256": "8dc82a12b6bfb8c497da7529bb52004573bd0f2eb024527c3b6bb1347c7e391f",
          "sha1": "117cbd6c4096bb8e339a07ccc67dc3f4d0ffa896",
          "md5": "ee4b36732526ec20a3e8cf351df5ba6c"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnanolog-wasm-js-1.2.2-SNAPSHOT.klib",
          "url": "klibnanolog-wasm-js-1.2.2-SNAPSHOT.klib",
          "size": 10268,
          "sha512": "c217de3a4441c926700f6b90a49f642534fb4f9584a14bf12244ac624d1a6252e7935b51cada57e43e4bd51c7000f09fb7a2f09c15072cbf1ac86b916efb29c1",
          "sha256": "8dc82a12b6bfb8c497da7529bb52004573bd0f2eb024527c3b6bb1347c7e391f",
          "sha1": "117cbd6c4096bb8e339a07ccc67dc3f4d0ffa896",
          "md5": "ee4b36732526ec20a3e8cf351df5ba6c"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "klibnanolog-wasm-js-1.2.2-SNAPSHOT-sources.jar",
          "url": "klibnanolog-wasm-js-1.2.2-SNAPSHOT-sources.jar",
          "size": 4825,
          "sha512": "cf3e94262ca9ccab2daa73322eab7a927eff99aa10aef3d5157576de177569d079832ba2acb42abb550f54e945774effd1abc76d9c93125fcae4651cf11481fc",
          "sha256": "124014f8f84367d282493f0373fb87240affd80ddddbeaa4493e10700dde81cc",
          "sha1": "aa872559900825d2189737d8a848719b704692ee",
          "md5": "721c8e3f96faf1f69019a6e817554b60"
        }
      ]
    }
  ]
}
